# Redirects
gems:
  - jekyll-redirect-from

# Base configuration
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "src", "node_modules"]
markdown: kramdown
highlighter: pygments

# Organization
org: CFPB

# Title
name: Design Manual
# We currently don't use this in the templates
subtitle: A set of principles and standards for the Consumer Financial Protection Bureau's design projects.

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/design-manual'

# Author/Organization info to be displayed in the templates
author:
  name: The Consumer Financial Protection Bureau
  url: https://cfpb.github.io/

repository:
  name: Design Manual
  url: https://github.com/cfpb/design-manual

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: 'static/img/logo_210.png'
logoalt: 'Consumer Financial Protection Bureau'

# Kramdown settings
kramdown:
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  parse_block_html: true

# Main Navigation
# List links that should appear in the main navigation (header) here
mainnav:
- text: Overview
  url: index.html
  internal: true
- text: Best practices
  url: best-practices/best-practices.html
  internal: true
- text: Brand guidelines
  url: brand-guidelines/brand-guidelines.html
  internal: true
- text: Global elements
  url: global-elements/global-elements.html
  internal: true
- text: Page components
  url: page-components/page-components.html
  internal: true
# - text: Data visualization
#   url: data-visualization/data-visualization.html
#   internal: true

# Secondary Navigation
# List links that should appear in the secondary navigation (sidebar) here
secondarynav:
- text: Home
  url: index.html
  internal: true
  category: Overview

# Best practices
- text: Accessibility best practices
  url: best-practices/accessibility-best-practices.html
  internal: true
  category: Best practices
- text: Design principles
  url: best-practices/design-principles.html
  internal: true
  category: Best practices
- text: Form best practices
  url: best-practices/form-best-practices.html
  internal: true
  category: Best practices


# Brand guidelines
- text: Beam pattern
  url: brand-guidelines/beam-pattern.html
  internal: true
  category: Brand guidelines
- text: Color
  url: brand-guidelines/color-principles.html
  internal: true
  category: Brand guidelines
- text: Illustrations
  url: brand-guidelines/illustration.html
  internal: true
  category: Brand guidelines
- text: Isocons
  url: brand-guidelines/isocons.html
  internal: true
  category: Brand guidelines
- text: Logo
  url: brand-guidelines/logo.html
  internal: true
  category: Brand guidelines
- text: Minicons
  url: brand-guidelines/minicons.html
  internal: true
  category: Brand guidelines
- text: Photography
  url: brand-guidelines/photography.html
  internal: true
  category: Brand guidelines
- text: Typography
  url: brand-guidelines/typography.html
  internal: true
  category: Brand guidelines
- text: Video
  url: brand-guidelines/video.html
  internal: true
  category: Brand guidelines


# Global elements
- text: Grid
  url: global-elements/grid.html
  internal: true
  category: Global elements
- text: Heroes
  url: global-elements/heroes.html
  internal: true
  category: Global elements


# Page components
- text: Buttons
  url: page-components/buttons.html
  internal: true
  category: Page components
- text: Expandables
  url: page-components/expandables.html
  internal: true
  category: Page components
- text: Featured content modules
  url: page-components/featured-content-module.html
  internal: true
  category: Page components
- text: Form fields
  url: page-components/form-fields.html
  internal: true
  category: Page components
- text: Links
  url: page-components/links.html
  internal: true
  category: Page components
# - text: Tables
#  url: page-components/tables.html
#  internal: true
#  category: Page components


# Footer Navigation
# List links that should appear in the footer navigation (footer) here
footernav:
- text: Home
  url: index.html
  internal: true
- text: DOCter Repo
  url: https://github.com/cfpb/DOCter
  internal: false
