# Redirects
plugins:
  - jekyll-redirect-from

# Base configuration
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "src", "node_modules"]
markdown: kramdown
highlighter: rouge

# Organization
org: CFPB

# Title
name: Design Manual
# We currently don't use this in the templates
subtitle: A set of principles and standards for the Consumer Financial Protection Bureau's design projects.

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/design-manual'

# Author/Organization info to be displayed in the templates
author:
  name: The Consumer Financial Protection Bureau
  url: https://cfpb.github.io/

repository:
  name: Design Manual
  url: https://github.com/cfpb/design-manual

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: 'static/img/logo_210.png'
logoalt: 'Consumer Financial Protection Bureau'

# Kramdown settings
kramdown:
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  parse_block_html: true

# Main Navigation
# List links that should appear in the main navigation (header) here
mainnav:
- text: Overview
  url: index.html
  internal: true
- text: Best practices
  url: best-practices/best-practices.html
  internal: true
- text: Brand guidelines
  url: brand-guidelines/brand-guidelines.html
  internal: true
- text: Global elements
  url: global-elements/global-elements.html
  internal: true
- text: Page components
  url: page-components/page-components.html
  internal: true
- text: Data visualization
  url: data-visualization/data-visualization.html
  internal: true

# Secondary Navigation
# List links that should appear in the secondary navigation (sidebar) here
secondarynav:
- text: Home
  url: index.html
  internal: true
  category: Overview

# Best practices
- text: Accessibility best practices
  url: best-practices/accessibility-best-practices.html
  internal: true
  category: Best practices
- text: Design principles
  url: best-practices/design-principles.html
  internal: true
  category: Best practices
- text: Form best practices
  url: best-practices/form-best-practices.html
  internal: true
  category: Best practices


# Brand guidelines
- text: Beam pattern
  url: brand-guidelines/beam-pattern.html
  internal: true
  category: Brand guidelines
- text: Color
  url: brand-guidelines/color-principles.html
  internal: true
  category: Brand guidelines
- text: Illustrations
  url: brand-guidelines/illustration.html
  internal: true
  category: Brand guidelines
- text: Isocons
  url: brand-guidelines/isocons.html
  internal: true
  category: Brand guidelines
- text: Logo
  url: brand-guidelines/logo.html
  internal: true
  category: Brand guidelines
- text: Minicons
  url: brand-guidelines/minicons.html
  internal: true
  category: Brand guidelines
- text: Photography
  url: brand-guidelines/photography.html
  internal: true
  category: Brand guidelines
- text: Typography
  url: brand-guidelines/typography.html
  internal: true
  category: Brand guidelines
- text: Video
  url: brand-guidelines/video.html
  internal: true
  category: Brand guidelines


# Global elements
- text: Browse page
  url: global-elements/browse-page.html
  internal: true
  category: Global elements
- text: Document detail page
  url: global-elements/document-detail.html
  internal: true
  category: Global elements
- text: Filterable list pages
  url: global-elements/filterable-list-pages.html
  internal: true
  category: Global elements
- text: Grid
  url: global-elements/grid.html
  internal: true
  category: Global elements
- text: Heroes
  url: global-elements/heroes.html
  internal: true
  category: Global elements
- text: Item introduction
  url: global-elements/item-introduction.html
  internal: true
  category: Global elements
- text: Landing page
  url: global-elements/landing-page.html
  internal: true
  category: Global elements
- text: Learn page
  url: global-elements/learn-page.html
  internal: true
  category: Global elements
- text: Sublanding page
  url: global-elements/sublanding-page.html
  internal: true
  category: Global elements
- text: Text introductions
  url: global-elements/text-introductions.html
  internal: true
  category: Global elements


# Page components
- text: 25/75 image and text
  url: page-components/25-75.html
  internal: true
  category: Page components
- text: 50/50 image and text
  url: page-components/50-50.html
  internal: true
  category: Page components
- text: Buttons
  url: page-components/buttons.html
  internal: true
  category: Page components
- text: Contact information
  url: page-components/contact-information.html
  internal: true
  category: Page components
- text: Email sign-up
  url: page-components/email-sign-up.html
  internal: true
  category: Page components
- text: Expandables
  url: page-components/expandables.html
  internal: true
  category: Page components
- text: Featured content modules
  url: page-components/featured-content-module.html
  internal: true
  category: Page components
- text: Filterable list control panel
  url: page-components/filter-control.html
  internal: true
  category: Page components
- text: Form fields
  url: page-components/form-fields.html
  internal: true
  category: Page components
- text: Full width text
  url: page-components/fullwidth-text.html
  internal: true
  category: Page components
- text: Link blob - half width
  url: page-components/half-width-link-blob.html
  internal: true
  category: Page components
- text: Link blob - third width
  url: page-components/third-width-link-blob.html
  internal: true
  category: Page components
- text: Links
  url: page-components/links.html
  internal: true
  category: Page components
- text: Modals
  url: page-components/modals.html
  internal: true
  category: Page components
- text: Sidebar/prefooter
  url: page-components/sidebar-prefooter.html
  internal: true
  category: Page components
- text: Tables
  url: page-components/tables.html
  internal: true
  category: Page components
- text: Wells
  url: page-components/wells.html
  internal: true
  category: Page components


# Data visualization
- text: Accessibility
  url: data-visualization/accessibility.html
  internal: true
  category: Data visualization
- text: Accuracy
  url: data-visualization/accuracy.html
  internal: true
  category: Data visualization
- text: Audience
  url: data-visualization/audience.html
  internal: true
  category: Data visualization
- text: Chart components
  url: data-visualization/chart-components.html
  internal: true
  category: Data visualization
- text: Chart types
  url: data-visualization/chart-types.html
  internal: true
  category: Data visualization
- text: Color
  url: data-visualization/color.html
  internal: true
  category: Data visualization
- text: Emphasis!
  url: data-visualization/emphasis.html
  internal: true
  category: Data visualization

# Footer Navigation
# List links that should appear in the footer navigation (footer) here
footernav:
- text: Home
  url: index.html
  internal: true
- text: DOCter Repo
  url: https://github.com/cfpb/DOCter
  internal: false
