# Base configuration
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "src", "node_modules"]
markdown: kramdown
highlighter: pygments

# Organization
org: CFPB

# Title
name: Design Manual
# We currently don't use this in the templates
subtitle: A set of principles and standards for the Consumer Financial Protection Bureau's design projects.

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/design-manual'

# Author/Organization info to be displayed in the templates
author:
  name: The Consumer Financial Protection Bureau
  url: https://cfpb.github.io/

repository:
  name: Design Manual
  url: https://github.com/cfpb/design-manual

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: 'static/img/logo_210.png'
logoalt: 'Consumer Financial Protection Bureau'

# Kramdown settings
kramdown:
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  parse_block_html: true

# Main Navigation
# List links that should appear in the main navigation (header) here
mainnav:
- text: Overview
  url: index.html
  internal: true
- text: Guides
  url: guides/guides.html
  internal: true
- text: Visual identity
  url: identity/identity.html
  internal: true
- text: UI toolkit
  url: ui-toolkit/ui-toolkit.html
  internal: true
# - text: Downloads
#   url: downloads/style-guide.html
#   internal: true

# Secondary Navigation
# List links that should appear in the secondary navigation (sidebar) here
secondarynav:
- text: Home
  url: index.html
  internal: true
  category: Overview
- text: Design principles
  url: guides/design-principles.html
  internal: true
  category: Guides
- text: Accessible interfaces
  url: guides/accessible-interfaces.html
  internal: true
  category: Guides
- text: Effective forms
  url: guides/effective-forms.html
  internal: true
  category: Guides
# - text: Filtering patterns
#   url: guides/filtering-patterns.html
#   internal: true
#   category: Guides
# - text: UX checklist
#   url: guides/ux-checklist.html
#   internal: true
#   category: Guides
- text: Logo
  url: identity/logo.html
  internal: true
  category: Visual identity
- text: Color
  url: identity/color-principles.html
  internal: true
  category: Visual identity
- text: Typography
  url: identity/typography.html
  internal: true
  category: Visual identity
- text: Minicons
  url: identity/minicons.html
  internal: true
  category: Visual identity
- text: Isocons
  url: identity/isocons.html
  internal: true
  category: Visual identity
- text: Illustration
  url: identity/illustration.html
  internal: true
  category: Visual identity
- text: Beam pattern
  url: identity/beams.html
  internal: true
  category: Visual identity
- text: Photography
  url: identity/photography.html
  internal: true
  category: Visual identity
- text: Video
  url: identity/video.html
  internal: true
  category: Visual identity
- text: Buttons
  url: ui-toolkit/buttons.html
  internal: true
  category: UI toolkit
- text: Expandables
  url: ui-toolkit/expandables.html
  internal: true
  category: UI toolkit
- text: Form fields
  url: ui-toolkit/form-fields.html
  internal: true
  category: UI toolkit
- text: Grid and layout
  url: ui-toolkit/grid-and-layout.html
  internal: true
  category: UI toolkit
- text: Links
  url: ui-toolkit/links.html
  internal: true
  category: UI toolkit
- text: Heroes
  url: ui-toolkit/heroes.html
  internal: true
  category: UI toolkit
- text: Featured content modules
  url: ui-toolkit/featured-content-module.html
  internal: true
  category: UI toolkit
- text: Modals
  url: ui-toolkit/modals.html
  internal: true
  category: UI toolkit
# - text: Pagination
#   url: ui-toolkit/pagination.html
#   internal: true
#   category: UI toolkit
# - text: Tables
#   url: ui-toolkit/tables.html
#   internal: true
#   category: UI toolkit
# - text: Tooltips
#   url: ui-toolkit/tooltips.html
#   internal: true
#   category: UI toolkit
# - text: Brand 2.0 style guide
#   url: downloads/style-guide.html
#   internal: true
#   category: Downloads
# - text: Logo suite
#   url: downloads/logo-suite.html
#   internal: true
#   category: Downloads
# - text: Minicon font and assets
#   url: downloads/minicons.html
#   internal: true
#   category: Downloads


# Footer Navigation
# List links that should appear in the footer navigation (footer) here
footernav:
- text: Home
  url: index.html
  internal: true
- text: DOCter Repo
  url: https://github.com/cfpb/DOCter
  internal: false
